### ISSUE TITLE
Integration in Adobe Launch not usable for business

### ISSUE THREAD

**Issue by kwin** [AdobeDocs/experience-manager-core-components.en#18]
Both data elements and rules require writing custom code.
That is usually not suitable for business people. Is there any better integration planned in Adobe Launch which would allow to just use the UI without coding for setting up tracking?

Issue in ./help/developing/data-layer/analytics-integration.md

**Comment by bohnertchris** [comment]
Hello @kwin. Thank you for the issue. This repository covers issues with the core components documentation rather than the product itself.  I know the development team is reviewing what can be done to make the integration easier, but it would be best to pose this question in the project repository.

https://github.com/adobe/aem-core-wcm-components
