### ISSUE TITLE
AEM Project Archetype should not be listed below AEM Core Components

### ISSUE THREAD

**Issue by nhirrle** [AdobeDocs/experience-manager-core-components.en#47]
AEM Project Archetype should not be listed below AEM Core Components, it is a total different project and deserves it's own space

Link reference https://experienceleague.adobe.com/docs/experience-manager-core-components/using/developing/archetype/overview.html?lang=en

**Comment by bohnertchris** [comment]
Thank you for creating this issue, @nhirrle. The project archetype was originally created to generate AEM projects based on the Core Components. We are aware that it has since grown and plan to separate the documentation in the future, but are unable to commit to a timeline on this given other priorities. The content is currently cross-linked and discoverable thought part of the Core Components documentation.

**Comment by nhirrle** [comment]
Thanks for the answer @bohnertchris . The AEM archetype (2015 or even earlier) existed before the very first release of AEM core wcm components (march 2017)
