### ISSUE TITLE
Not able to use number element for ordering a content fragment list

### ISSUE THREAD

**Issue by rnituadobe** [AdobeDocs/experience-manager-core-components.en#49]
Issue in ./help/components/content-fragment-list.md

Order By - Field of the content fragment model by which the list will be ordered
Only text fields (including numeric, date, and time) are selectable.

should be changed to:

Order By - Field of the content fragment model by which the list will be ordered
Only text fields,date, and time (excluding numeric) are selectable.

Date & time :  https://github.com/adobe/aem-core-wcm-components/issues/2376 - Fixed in 2.20.0
Number : https://github.com/adobe/aem-core-wcm-components/issues/2396 - will be fixed in future release

**Label: DocBugBlitz2023**

**Comment by aheim0** [comment]
@adobe export issue to Jira project CQDOC

**Comment by bohnertchris** [comment]
The issue reported was already fixed with Core Components release 2.22.4. Therefore there is nothing that needs to be adjusted in the documentation.

https://github.com/adobe/aem-core-wcm-components/issues/2396

We appreciate suggestions and feedback on our documentation, but any changes required due to errors introduced in the software should be documented as a known issue. We do not update documentation to accommodate errors or bugs.

https://github.com/AdobeDocs/experience-manager-core-components.en/blob/main/guidelines.md#we-do-not-generally-document-bugs-or-their-workarounds
